import axios from "axios";
import globals from "./globals";

class AuthService {
    /**
     * Performs the invisible handshake with the backend.
     * @param turnstileToken The one-time token generated by the Cloudflare widget.
     * @returns boolean indicating if the handshake (and cookie placement) was successful.
     */
    public async handshake(turnstileToken: string): Promise<boolean> {
        try {
            const res = await axios.post<{ success: boolean; token?: string }>(
                globals.authUrl + "handshake", 
                { turnstileToken },
                { 
                    // Crucial: Allows the browser to receive and store the HttpOnly cookie
                    withCredentials: true 
                }
            );

            // If you are using Header-based JWT instead of Cookies:
            // if (res.data?.success && res.data?.token) {
            //     axios.defaults.headers.common['Authorization'] = `Bearer ${res.data.token}`;
            // }

            return res.data?.success;
        }
        catch (err) {
            console.error("Handshake failed:", err);
            return false;
        }
    }

    /**
     * Optional: Check if the current session is still valid (using the invisible cookie)
     */
    public async checkAuth(): Promise<boolean> {
        try {
            const res = await axios.get<{ success: boolean }>(
                globals.authUrl + "me", 
                { withCredentials: true }
            );
            return res.data?.success;
        } catch (err) {
            return false;
        }
    }
}

const authService = new AuthService();
export default authService;